Repository klarna/electron-redux, pull requests merged in 2020-11, with the labels that each got.

#281 chore: add README & LICENSE
  LICENSE.md
  README.md
Labels: chore 🧹, hacktoberfest-accepted, v2

#280 feat: make renderer state initialization synchronous by default
  package.json
  src/constants/index.ts
  src/fetchState/fetchInitialState.ts
  src/fetchState/fetchInitialStateAsync.ts
  src/fetchState/index.ts
  src/fetchState/replaceState.ts
  src/mainStateSyncEnhancer.ts
  src/options/MainStateSyncEnhancerOptions.ts
  src/options/RendererStateSyncEnhancerOptions.ts
  src/rendererStateSyncEnhancer.ts
  src/utils/actions.ts
  tests/e2e.spec.ts
  tests/e2e/main/index.ts
  tests/e2e/renderer/index.ts
  tests/fetchState.spec.ts
  yarn.lock
Labels: enhancement ✨, hacktoberfest-accepted, v2

#277 docs: setup base documentation website
  .github/workflows/gh-pages.yml
  docs/.gitignore
  docs/README.md
  docs/babel.config.js
  docs/blog/2019-05-28-hola.md
  docs/blog/2019-05-29-hello-world.md
  docs/blog/2019-05-30-welcome.md
  docs/docs/contributing.md
  docs/docs/installation.md
  docs/docs/markdown.md
  docs/docs/mdx.md
  docs/docs/overview.md
  docs/docusaurus.config.js
  docs/package.json
  docs/sidebars.js
  docs/src/css/custom.css
  docs/src/pages/index.js
  docs/src/pages/styles.module.css
  docs/static/.nojekyll
  docs/static/img/favicon.ico
  docs/static/img/logo.svg
  docs/static/img/undraw_docusaurus_mountain.svg
  docs/static/img/undraw_docusaurus_react.svg
  docs/static/img/undraw_docusaurus_tree.svg
  docs/yarn.lock
Labels: documentation 📚, v2
