Repository klarna/electron-redux, pull requests merged in 2021-02, with the labels that each got.

#290 docs: adding initial content for v2
  docs/blog/2019-05-28-hola.md
  docs/blog/2019-05-29-hello-world.md
  docs/blog/2019-05-30-welcome.md
  docs/docs/api/api-reference.md
  docs/docs/contributing.md
  docs/docs/faq/faq-general.md
  docs/docs/installation.md
  docs/docs/introduction/core-concepts.md
  docs/docs/introduction/getting-started.md
  docs/docs/introduction/installation.md
  docs/docs/markdown.md
  docs/docs/mdx.md
  docs/docs/overview.md
  docs/docs/recipes/apply-middleware.md
  docs/docs/recipes/typescript.md
  docs/docs/v1/migrating-from-v1-to-v2.md
  docs/docs/v1/version-1-x.md
  docs/docusaurus.config.js
  docs/sidebars.js
  docs/src/pages/index.js
Labels: documentation 📚, v2

#296 fix(#285): add composeWithStateSync to resolve issues with enhancer order
  README.md
  docs/docs/faq/faq-general.md
  docs/docs/introduction/getting-started.md
  src/composeWithStateSync.ts
  src/forwardAction.ts
  src/index.ts
  src/mainStateSyncEnhancer.ts
  src/options/MainStateSyncEnhancerOptions.ts
  src/options/RendererStateSyncEnhancerOptions.ts
  src/options/StateSyncOptions.ts
  src/rendererStateSyncEnhancer.ts
  src/stateSyncEnhancer.ts
  src/utils/actions.ts
  src/utils/misc.ts
  tests/typescript/composeWithStateSync.ts
Labels: v2

#299 chore: adding basic example of usage in raw scenario + moving integration tests
  .babelrc.js
  .vscode/settings.json
  examples/basic/package.json
  examples/basic/src/main/index.ts
  examples/basic/src/renderer/index.html
  examples/basic/src/renderer/index.ts
  examples/basic/src/store/actions.ts
  examples/basic/src/store/index.ts
  examples/basic/src/store/reducers.ts
  examples/basic/tsconfig.json
  examples/basic/webpack.config.js
  examples/basic/webpack.main.js
  examples/basic/webpack.renderer.js
  examples/basic/yarn.lock
  package.json
  src/mainStateSyncEnhancer.ts
  src/rendererStateSyncEnhancer.ts
  src/stateSyncEnhancer.ts
  tests/e2e.spec.ts
  tests/e2e/main/index.ts
  tests/e2e/renderer/index.html
  tests/e2e/renderer/index.ts
  yarn.lock
Labels: chore 🧹, v2
